dist: bionic
language: go

go:
  - 1.13.x
  - 1.14.x
  - master

script:
  - go test -v -race -timeout 10s -coverprofile=ehtml.cov -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -f '*.cov'